Repository pr3b/penateam, pull requests merged in 2023-08, with the labels that each got.

#23 Update UI pricing
  jsconfig.json
  pages/auth/verify-request.jsx
  pages/components/Pricing.js
  pages/dashboard/DashboardMainContent.js
  pages/dashboard/components/DashboardSidebar/SidebarDesktop.js
  pages/dashboard/components/UserDropdown.js
  pages/dashboard/page/KanbanBoard.js
  pages/dashboard/page/SubscribeStatus.js
  pages/dashboard/page/TableInvoices.js
  public/assets/images/dashboard/bottmImage.svg
  styles/globals.css
Labels: documentation

#24 Implement midtrans payment
  package.json
  pages/_document.js
  pages/api/braintree/checkout.js
  pages/api/braintree/create-subscription.js
  pages/api/braintree/get-client-token.js
  pages/api/midtrans/get-snap-token.js
  pages/components/Pricing.js
  pages/customer.js
  utils/braintree.js
  utils/currencyConverter.js
  utils/midtrans.js
Labels: documentation, enhancement

#25 form design
  package-lock.json
  package.json
  pages/components/Benefit.js
  pages/components/Brand.js
  pages/components/Developing.js
  pages/components/Pricing.js
  pages/components/Work.js
  pages/customer.js
  styles/globals.css
Labels: documentation, enhancement

#27 marquee infinite fix
  package-lock.json
  package.json
  pages/components/Logo2.js
  pages/index.js
  styles/globals.css
Labels: bug, documentation

#29 Implement Midtrans payment
  pages/api/midtrans/get-snap-token.js
  pages/components/Pricing.js
  pages/customer.js
  utils/midtrans.js
Labels: documentation, duplicate

#33 Paypal integrations
  package.json
  pages/MidtransSuccess.js
  pages/api/log/log.js
  pages/api/midtrans/get-snap-token.js
  pages/api/midtrans/invoices.js
  pages/api/midtrans/success-payment-check.js
  pages/api/paypal/subscription.js
  pages/components/Pricing.js
  pages/customer.js
  pages/index.js
  prisma/schema.prisma
  utils/midtrans.js
Labels: duplicate

#34 Paypal integrations
  pages/customer.js
Labels: documentation, duplicate

#35 change button click
  pages/customer.js
Labels: documentation, duplicate
